spring:
  application:
    name: locme
  
  datasource:
    url: jdbc:postgresql://localhost:5432/locme
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  security:
    jwt:
      secret: ${JWT_SECRET:T807GhPnTJoAQ/VHSoIPQ3mb5ZperAGqaj8Rskr/kyo=}
      expiration: 86400000 # 24 heures

server:
  port: 8080

logging:
  level:
    com.locme: DEBUG
    org.springframework.security: DEBUG

# Configuration Stripe
stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_your_stripe_publishable_key}

# Documentation API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true